global:
  scrape_interval:     15s
  evaluation_interval: 5s
  scrape_timeout:     1m
  external_labels:
    monitor: 'codelab-monitor'

scrape_configs:
  - job_name: 'file_sd_targets'
    file_sd_configs:
      - files:
        - 'targets.json'
