version: '3.4'

services:

  prometheus:
    build:
      context: prometheus/
    volumes:
      - ./prometheus/config/prometheus.yml:/usr/share/prometheus/config/prometheus.yml:ro
    ports:
      - "9090:9090"
